### ISSUE TITLE
Support of key option for yaml including alias

### ISSUE THREAD

**Issue by k2tzumi** [joker1007/yaml_vault#10]
If yaml includes alias, encrypt it with the key option specified.

`bundle exec yaml_vault encrypt plain.yml -o encrypted.yml -k 'foo'`

* plain.yml
```yml
foo: &foo
  x: 1
  y: 2
bar:
  <<: *foo
  z: 3
```

https://github.com/joker1007/yaml_vault/blob/2e37a160c0cf8dc584c870beff7f0e1c9ef4bffc/lib/yaml_vault.rb#L24

In order to encrypt the specific key or less after expansion, places that don't want to be plain have been expanded.
(Foo.x, foo.y are encrypted but bar.x, bar.y are not encrypted)

* encrypted.yml(As-is)
```yml
foo:
  x: encrypted-1
  y: encrypted-2
bar:
  x: 1
  y: 2
  z: 3
```

* encrypted.yml(expect)
```yml
foo: &foo
  x: encrypted-1
  y: encrypted-2
bar:
  <<: *foo
  z: 3
```
Or

```yml
foo:
  x: encrypted-1
  y: encrypted-2
bar:
  x: encrypted-1
  y: encrypted-2
  z: 3
```
